name: Test Token Access to macOS Repo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test access to trifecta-native-agent-main
        env:
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
        run: |
          echo "Testing CROSS_REPO_TOKEN access to trifecta-native-agent-main..."
          
          # Test 1: Can we list workflows?
          echo "✓ Test 1: List workflows..."
          gh workflow list --repo Carmel-Labs-Inc/trifecta-native-agent-main || echo "❌ Cannot list workflows"
          
          # Test 2: Can we list recent runs?
          echo "✓ Test 2: List workflow runs..."
          gh run list --repo Carmel-Labs-Inc/trifecta-native-agent-main --limit 5 || echo "❌ Cannot list runs"
          
          # Test 3: Can we view repo info?
          echo "✓ Test 3: View repo info..."
          gh repo view Carmel-Labs-Inc/trifecta-native-agent-main || echo "❌ Cannot view repo"
          
          echo ""
          echo "✅ If all tests passed, CROSS_REPO_TOKEN has access to trifecta-native-agent-main"
          echo "❌ If any failed, you need to update the token permissions"

